package org.techinowave.foody.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFFF2424F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE2DFFF)
val onPrimaryContainerLight = Color(0xFF15134A)
val secondaryLight = Color(0xFF5D5C71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE3E0F9)
val onSecondaryContainerLight = Color(0xFF1A1A2C)
val tertiaryLight = Color(0xFF7A5368)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD8EA)
val onTertiaryContainerLight = Color(0xFF2F1124)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFCF8FF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFFCF8FF)
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFE4E1EC)
val onSurfaceVariantLight = Color(0xFF47464F)
val outlineLight = Color(0xFF787680)
val outlineVariantLight = Color(0xFFC8C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303036)
val inverseOnSurfaceLight = Color(0xFFF3EFF7)
val inversePrimaryLight = Color(0xFFC3C0FF)
val surfaceDimLight = Color(0xFFDCD9E0)
val surfaceBrightLight = Color(0xFFFCF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F2FA)
val surfaceContainerLight = Color(0xFFF0ECF4)
val surfaceContainerHighLight = Color(0xFFEAE7EF)
val surfaceContainerHighestLight = Color(0xFFE5E1E9)


val primaryDark = Color(0xFFF2424F)
val onPrimaryDark = Color(0xFF2B2A60)
val primaryContainerDark = Color(0xFF424178)
val onPrimaryContainerDark = Color(0xFFE2DFFF)
val secondaryDark = Color(0xFFC7C4DD)
val onSecondaryDark = Color(0xFF2F2F42)
val secondaryContainerDark = Color(0xFF464559)
val onSecondaryContainerDark = Color(0xFFE3E0F9)
val tertiaryDark = Color(0xFFEAB9D2)
val onTertiaryDark = Color(0xFF472639)
val tertiaryContainerDark = Color(0xFF603C50)
val onTertiaryContainerDark = Color(0xFFFFD8EA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE5E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE5E1E9)
val surfaceVariantDark = Color(0xFF47464F)
val onSurfaceVariantDark = Color(0xFFC8C5D0)
val outlineDark = Color(0xFF928F9A)
val outlineVariantDark = Color(0xFF47464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E1E9)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF5A5892)
val surfaceDimDark = Color(0xFF131318)
val surfaceBrightDark = Color(0xFF39383F)
val surfaceContainerLowestDark = Color(0xFF0E0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF201F25)
val surfaceContainerHighDark = Color(0xFF2A292F)
val surfaceContainerHighestDark = Color(0xFF35343A)







